### ISSUE TITLE
It is not available to play back for any video

### ISSUE THREAD

**Issue by matthuo333** [lubo/KODI-Popcorn-Time#5] opened 2022-03-15 02:59 UTC
After installing the latest version of the test, you can enter the UI of the plugin, but you can not play any movies, and you can directly jump out after opening

**Comment by lubo** [comment] 2022-03-15 08:38
No idea what's "the test" you're talking about. Also, I can play movies and TV shows just fine on Arch Linux and on LibreELEC. And since you've provided no information that'd make it possible to reproduce the alleged problem, I'm closing the issue as invalid. I may reopen it once you provide the full Kodi log, which shows that there's actually a problem.

**Closed as completed by lubo** 2022-03-15 08:38 UTC

**Comment by AkashKrx** [comment] 2022-10-17 10:28
I am assuming @matthuo333 is having the same problem as me which is on Kodi v19.3 and plugin v2.0.1 for Android TV

I am not able to play any of the movies a loading popup shows up for a fraction of a second and disappears and that's it. For TV Shows there is no option to play.

I believe the issue is dependencies of this plugin are not installed and I haven't found a way to figure out which dependencies this plugin uses.

**Comment by Blisk** [comment] 2022-11-21 07:13
I tested this and it works on windows 10 but doesn't work on android TV box.

**Comment by lubo** [comment] 2022-11-21 19:07
Again, I can't help you without logs.

**Comment by Blisk** [comment] 2022-11-21 19:50
I am aware of that. Where I can find logs on android kodi for this plugin?

**Comment by lubo** [comment] 2022-11-21 19:53
There are no plugin-specific log files, so see [Log file](https://kodi.wiki/view/Log_file).
